name: ✨ Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input to help make Mustache Cashstage better.

  - type: checkboxes
    id: checks
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed these steps before submitting.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [Contributing Guide](../docs/CONTRIBUTING.md)
          required: true
        - label: I have reviewed the [project roadmap](../docs/CHANGELOG.md) to see if this is already planned
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Dashboard & Visualization
        - Data Sources & Integration
        - User Interface & Experience
        - Performance & Optimization
        - Authentication & Security
        - Developer Experience
        - Analytics & Reporting
        - Mobile & Responsive
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocks major workflows)
        - High (would significantly improve experience)
        - Medium (nice to have, improves workflow)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches could be...

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Provide user stories that describe how this feature would be used.
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].

        Example:
        As a marketing manager, I want to compare campaign performance across multiple time periods so that I can identify trends and optimize future campaigns.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific functionality should this feature include?
      placeholder: |
        - [ ] Feature should allow...
        - [ ] Users should be able to...
        - [ ] The interface should display...

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      multiple: true
      options:
        - Marketing Managers
        - Data Analysts
        - Dashboard Viewers
        - System Administrators
        - Developers
        - End Users
        - All Users

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any visual mockups, wireframes, or examples, please share them here.
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, dependencies, or constraints to consider?
      placeholder: This feature might require...

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: How would this feature benefit the business or users?
      placeholder: This feature would help by...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Scope
      description: What aspects would this feature affect?
      options:
        - label: Frontend UI changes
        - label: Backend API changes
        - label: Database schema changes
        - label: New third-party integrations
        - label: Performance considerations
        - label: Security implications
        - label: Documentation updates
        - label: Testing requirements

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, research, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...
