name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-review:
    if: |
      (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip-claude-review')) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/claude review'))
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Get diff
        id: get-diff
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.event.pull_request.base.ref }}
            git diff origin/${{ github.event.pull_request.base.ref }}..HEAD > diff.txt
          else
            PR_NUMBER=${{ github.event.issue.number }}
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            git fetch origin main
            git diff origin/main..pr-$PR_NUMBER > diff.txt
          fi
          
      - name: Claude Review
        id: claude-review
        uses: anthropics/claude-code@beta
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-opus-20240229
          max_tokens: 4096
          temperature: 0.3
          system_prompt: |
            You are a senior software engineer reviewing code changes. 
            Provide constructive feedback focusing on:
            - Code quality and best practices
            - Potential bugs or security issues
            - Performance considerations
            - Maintainability and readability
            - Test coverage
            
            Be concise but thorough. Use markdown formatting.
            Start with a brief summary, then provide detailed feedback.
            End with a clear recommendation (approve, request changes, or comment).
          prompt: |
            Please review the following code changes:
            
            ```diff
            $(cat diff.txt)
            ```
            
            Repository: ${{ github.repository }}
            PR Title: ${{ github.event.pull_request.title || 'Manual Review Request' }}
            PR Description: ${{ github.event.pull_request.body || 'No description provided' }}
          
      - name: Post review comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = `${{ steps.claude-review.outputs.response }}`;
            
            if (context.eventName === 'pull_request') {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                body: review,
                event: 'COMMENT'
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: review
              });
            }