    name: Claude Code Review
    on:
      pull_request:
        types: [opened, synchronize, reopened]
      issue_comment:
        types: [created]
    permissions:
      contents: read
      pull-requests: write
      issues: write
    jobs:
      claude_code_review:
        runs-on: ubuntu-latest
        if: |
          (github.event_name == 'pull_request') ||
          (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/claude'))
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Get PR diff
            id: get_diff
            if: github.event_name == 'pull_request'
            run: |
              git fetch origin ${{ github.event.pull_request.base.sha }}
              git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr.diff
              echo "diff=$(cat pr.diff)" >> $GITHUB_OUTPUT

          - name: Set prompt
            id: set_prompt
            run: |
              if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                PROMPT="As an expert code reviewer, please analyze the following pull request diff and provide feedback. Focus on identifying potential bugs, improving code clarity and maintainability, and ensuring adherence to best practices. Do not comment on style unless it impacts readability or performance. Structure your feedback with a high-level summary followed by specific, actionable comments referencing the file and line numbers. The diff is: \n\n${{ steps.get_diff.outputs.diff }}"
              else
                PROMPT="${{ github.event.comment.body }}"
              fi
              echo "prompt<<EOF" >> $GITHUB_OUTPUT
              echo "$PROMPT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT

          - name: Call Claude API
            id: call_claude
            uses: anthropic-ai/claude-action@v1
            with:
              anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
              prompt: ${{ steps.set_prompt.outputs.prompt }}

          - name: Comment on PR/Issue
            uses: actions/github-script@v7
            with:
              script: |
                const output = `${{ steps.call_claude.outputs.response }}`;
                if (context.eventName === 'pull_request') {
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                  });
                } else {
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                  });
                }

